# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from imprcm_uuid_server.models.base_model_ import Model
from imprcm_uuid_server import util


class UuidBracketed(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self):  # noqa: E501
        """UuidBracketed - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'UuidBracketed':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The uuid_bracketed of this UuidBracketed.  # noqa: E501
        :rtype: UuidBracketed
        """
        return util.deserialize_model(dikt, cls)
